#!/bin/bash
server=192.168.1.92
workdir="$HOME/talks"

config="$HOME/.config/talkrec/sound_sender.bash"
shopt -s nullglob
shopt -u failglob
confdir=$(dirname "$config")
. "$config"
if [ ! -r "$pw_file" ]; then
	echo "Невозможно прочесть файл $pw_file" >&2
	exit 2
fi
user=$(basename "$pw_file" .pw)
if [ -z "$user" ]; then
	echo "Невозможно определить пользователя на $server по имени файла $pw_file" >&2
	exit 2
fi
mkdir -p "$workdir" || exit 2
cd "$workdir" || exit 2
while true; do
	for f in *.wav; do
		if [ -f "$f.meta" ]; then
			rsync -t --password-file "$pw_file" -- "$f" "$f.meta" "rsync://$user@$server/queue/" &&
				touch -- "$f.flag" &&
				rsync -t --password-file "$pw_file" -- "$f.flag" "rsync://$user@$server/queue/" &&
				rm -f -- "$f" "$f.meta" "$f.flag"
		fi
	done
	sleep 12
done
