#!/usr/bin/tclsh
package require cmdline

array set ::opt [::cmdline::getoptions ::argv {
    {-key.arg "" ""}
    {-server.arg "" ""}
    {-port.arg "" ""}
    {-ipv4 ""}
    {-silent ""}
}]

set soundFile [lindex $::argv 0]

proc back_report {n script} {
    while {$n > 0} {
	puts "Обратный отсчет: $n"
	flush stdout
	exec sleep 1
	incr n -1
    }
    uplevel $script
}

if {![regexp {(\d+)\.\w+$} $soundFile - n]} {set n 1}

switch $n {
    0 {back_report 0 {socket 127.0.0.2 11}}
    3 {back_report 3 {error 500}}
    5 {back_report 5 {exit 1}}
    default {back_report $n {exit 0}}
}
