#!/usr/bin/tclsh
set ::scriptDir [file dirname [file normalize [info script]]]
set ::talkrecDir [file dirname $::scriptDir]
set ::libtcldir [file join [file dirname [file dirname [file normalize [info script]]]] recorder libtcl]
source [file join $libtcldir common.tcl]
source [file join $libtcldir install.tcl]

proc main {} {
    getOptions - {}
    if {![dict exists $::paths serverBin]} {
	dict set ::paths serverBin [file normalize [file join $::talkrecDir server]]
    }
    installServiceFiles [glob -directory [file join [dict get $::paths serverBin] example] *.service]
}

runMain
