#!/usr/bin/tclsh
set scriptDir [file normalize [file dirname [info script]]]
set libtcldir [file join [file dirname [file dirname [file normalize [info script]]]] recorder libtcl]
source [file join $libtcldir common.tcl]
source [file join $libtcldir install.tcl]

getOptions - {}
if {[info exists ::env(LD_LIBRARY_PATH)]} {
    set libpath [split $::env(LD_LIBRARY_PATH) :]
} else {
    set libpath {}
}
if {[lsearch -exact $libpath /usr/local/lib] < 0} {lappend libpath /usr/local/lib}
run set ::env(LD_LIBRARY_PATH) [join $libpath :]
run set ::env(DISPLAY) :0
run execInLoop feeder $scriptDir/talkrec-feeder
run execInLoop rsyncd /usr/bin/rsync --daemon --no-detach --config [configFile rsyncd.conf]
run execInLoop show-results $scriptDir/show-results.tcl
vwait forever
