#!/bin/sh
# -*- tcl -*- \
exec tclsh "$0" ${1+"$@"}

proc feedFile {soundFile} {
    puts "Recognizing $soundFile..."
    set pipe [open [list | asrclient-cli.py --key internal --server localhost --ipv4 --silent $soundFile] r]
    set textH [open $soundFile.tmp w]
    while {![eof $pipe]} {
	set line [gets $pipe]
	if {[regexp {^from } $line] || [regexp {^\s*$} $line]} {} else {puts $textH $line}
    }
    close $textH
    close $pipe
    file rename -force -- $soundFile.tmp $soundFile.text
    puts "$soundFile -> $soundFile.text"
}

proc runQueue {} {
    set flagFiles [glob -nocomplain -directory [file normalize $::config(workdir)] *.flag]
    foreach flagFile $flagFiles {
	set soundFile [file rootname $flagFile]
	file delete -- $flagFile
	if [catch {feedFile $soundFile} err] {
	    file delete -- $soundFile.tmp
	    puts stderr $err
	} else {
	    file delete -- $soundFile
	}
    }
    after 500 runQueue
}

proc readConfig {configFile} {
    array set ::config {workdir ~/queue}
    array set ::servers {localhost 1}
}

proc main {} {
    if {[catch {readConfig ~/.config/talkrec/dispatcher.tcl} err]} {
	puts stderr $err
	exit 2
    }
    file mkdir $::config(workdir)
    runQueue
    vwait forever
}

main
