#!/usr/bin/tclsh

set libtcldir [file join [file dirname [file dirname [file normalize [info script]]]] recorder libtcl]
source [file join $libtcldir common.tcl]
source [file join $libtcldir install.tcl]
package require tdbc
package require tdbc::postgres

proc main {} {
    getOptions [configDictFile dispatcher] {}
    set ::config [readDict $::opt(-config)]
    set ::database [dictGetOr talkrec $::config database]
    set ::irConfig [readDict [configDictFile install-recorder]]
    if {[catch {dict get $::irConfig serverAddr} ::serverAddr]} {
	error "В [configDictFile install-recorder] не указан serverAddr"
    }
    array set ::hostState {}
    array set ::hostVersion {}
    asyncLoop runHostChecks 60000 runHostChecks
    after 8000 {asyncLoop fixHostCheckResults 60000 fixHostCheckResults}
    socket -server acceptConfigRequest 17120
    vwait exit
}

proc runHostChecks {} {
    safelog {info "runHostChecks heartbeat"}
    ::tdbc::postgres::connection create dbc -database $::database
    try {
	set hosts [lmap row [dbc allrows -as lists {select ip from record_station}] {lindex $row 0}]
    } finally {dbc close}
    foreach host $hosts {asyncConnect $host 17119 2000 recorder onConnectToRecorder onDisconnectFromRecorder}
}

proc onConnectToRecorder {connData} {
    safelog {debug [list onConnectToRecorder $connData]}
    set chan [connDataChan $connData]
    fconfigure $chan -buffering line
    after 4000 [list asyncDisconnect $connData replyTimeout]
    catchDbg {puts $chan [versionRequest]}
    fileevent $chan readable [list asyncOnReply $connData 4000 serveReplyFromRecorder]
}

proc recordError {connData message} {
    if {[catch {connDataHost $connData} host]} {
	safelog {error "Нет ключа host в [list $connData]\n  +проблема: $message"}
    } else {
	recordState $host $message
    }
}

proc fixHostCheckResults {} {
    safelog {info "fixHostCheckResults heartbeat"}
    set states [array get ::hostState]
    set versions [array get ::hostVersion]
    array set ::hostState {}
    array set ::hostVersion {}
    if {[dict size $states] + [dict size $versions] == 0} return
    ::tdbc::postgres::connection create dbf -database $::database
    try {
	dict for {host state} $states {
	    foreach {message seconds} $state break
	    set timestamp [clock format $seconds -format "%Y-%m-%d %H:%M:%S%z"]
	    dbf allrows {update record_station set state = :message, state_at = :timestamp where ip = :host and (state <> 'отключен' or state is null)} [dict create message $message timestamp $timestamp host $host]
	}
	dict for {host vd} $versions {
	    dict set vd host $host
	    dbf allrows {update record_station set version = :version, time_diff = :timeDiff where ip = :host} $vd
	}
    } finally {dbf close}
}

proc recordState {host message} {
    set ::hostState($host) [list $message [clock seconds]]
}

proc recordVersion {host vdict} {
    if {[catch {dict get $vdict version} version]} {set version ""}
    if {$version eq ""} {set version "доисторическая"}
    set vd [dict create version $version]
    if {[dict exists $vdict now]} {
	dict set vd timeDiff [expr {[dict get $vdict now] - [clock seconds]}]
    }
    set ::hostVersion($host) $vd
}

proc onDisconnectFromRecorder {connData reason message} {
    safelog {debug [list onDisconnectFromRecorder $connData $reason $message]}
    switch $reason {
	connectTimeout {recordError $connData "недоступна"}
	replyTimeout {recordError $connData "не ответила"}
	error {
	    if {$message eq "connection refused"} {
		recordError $connData "не работает"
	    } else {
		recordError $connData $message
	    }
	}
	ok {
	    if {[catch {connDataHost $connData} host]} {
		safelog {error "Нет ключа host в [list $connData]"}
	    } else {
		safelog {debug "$host [list $message]"}
		recordVersion $host $message
		recordState $host "работает"
	    }
	}
	default {recordError $connData $message}
    }
}

proc serveReplyFromRecorder {connData line} {
    safelog {debug [list serveReplyFromRecorder $connData $line]}
    if {[catch {parseObject $line} obj dbg]} {
	debugStackTrace $dbg
	return [list ok {}]
    }
    return [list ok [dict filter $obj key version now]]
}

proc versionRequest {} {simpleDictToJSON [dict create msgId [nextMessageId] req version] 0}

proc nextMessageId {} {incr ::nextMessageId}

proc acceptConfigRequest {sock addr port} {
    safelog {debug [list acceptConfigRequest $sock $addr $port]}
    fconfigure $sock -blocking 0 -buffering line
    set connData [dict create chan $sock host $addr port $port pass {} onDisconnect configRequestDisconnect]
    after 10000 [list asyncDisconnect $connData replyTimeout]
    fileevent $sock readable [list asyncOnReply $connData 10000 serveConfigRequest]
}

proc configRequestDisconnect {connData reason message} {
    safelog {debug [list configRequestDisconnect $connData $reason $message]}
    switch $reason {
	waitTimeout {
	    safelog {warning "Истекло время ожидания запроса конфигурациии от [connDataHost $connData]"}
	}
	error {
	    safelog {error "Ошибка в соединении [connDataHost $connData] с конфигуратором: $message"}
	}
    }
}

proc serveConfigRequest {connData line} {
    safelog {debug [list serveConfigRequest $connData $line]}
    if {[catch {parseObject $line} req dbg]} {
	debugStackTrace $dbg
	return [list error "serveConfigRequest: непонятный запрос от [connDataHost $connData]: $line"]
    }
    set requestedConfigs [dictGetOr {} $req configurations]
    if {[llength $requestedConfigs] == 0} {return {ok "serveConfigRequest: никаких конфигураций не спросили"}}
    set db [::tdbc::postgres::connection create dbcr -database $::database]
    try {
	if {[catch {dict get [siteAndHeadsetForIP $db [connDataHost $connData]] site_id} siteId dbg]} {
	    debugStackTrace $dbg
	    return [list error "serveConfigRequest: $siteId"]
	}
	set reply [dict create]
	foreach cfg $requestedConfigs {
	    switch $cfg {
		employees {dict set reply $cfg [genEmployeesConfig $db $siteId 0]}
		record_manager {dict set reply $cfg [genRecordManagerConfig $db $siteId $::serverAddr 0]}
	    }
	}
	::json::write indented 0
	set replyJson [::json::write object {*}$reply]
	puts [connDataChan $connData] $replyJson
    } finally {$db close}
    return {ok {}}
}

runMain
