#!/usr/bin/tclsh
set scriptdir [file normalize [file dirname [info script]]]
set libtcldir [file join $scriptdir libtcl]
source [file join $libtcldir common.tcl]
source [file join $libtcldir install.tcl]

getOptions - {}
run set ::env(DISPLAY) :0
run execInLoop recorder $scriptdir/recorder
run execInLoop sound_sender $scriptdir/sound_sender
run execInLoop record_manager $scriptdir/record_manager
vwait forever
