#!/usr/bin/tclsh
set scriptdir [file normalize [file dirname [info script]]]
set libtcldir [file join $scriptdir libtcl]
source [file join $libtcldir common.tcl]
source [file join $libtcldir install.tcl]

set ::env(DISPLAY) :0
execInLoop recorder $scriptdir/recorder
execInLoop sound_sender $scriptdir/sound_sender
execInLoop record_manager $scriptdir/record_manager
vwait forever
