#!/usr/bin/tclsh
set scriptdir [file normalize [file dirname [info script]]]
set libtcldir [file join $scriptdir libtcl]
source [file join $libtcldir common.tcl]
source [file join $libtcldir install.tcl]

set ::env(DISPLAY) :0
runProcInLoop $scriptdir/recorder
runProcInLoop $scriptdir/sound_sender
runProcInLoop $scriptdir/record_manager
vwait forever
